[[module.imports]]
path = "github.com/hbstack/giscus"

[[module.imports]]
path = "github.com/hbstack/blog"

[params.hugopress.modules.hb-blog-comments-giscus.hooks.hb-blog-post-comments]

[params.hugopress.modules.hb-blog-comments-giscus.hooks.body-end]
