main:

  - name: About
    identifier: aboutme
    weight: 100
    url: /about
    params:
      header: About Me
      icon:
        vendor: bs
        name: person-badge

  - name: Achievements
    identifier: awardsandachievements
    weight: 101
    url: /achievements
    params:
      header: Awards and Achievements
      icon:
        vendor: bs
        name: patch-check