main:

  - name: About
    identifier: aboutme
    weight: 100
    url: /about
    params:
      header: About Me
      icon:
        vendor: bs
        name: person-badge

  - name: Achievements
    identifier: awardsandachievements
    weight: 101
    url: /achievements
    params:
      header: Awards and Achievements
      icon:
        vendor: bs
        name: patch-check

  - name: Events and Projects
    identifier: eventsandprojects
    weight: 102
    url: /projects
    params:
      header: Events and Projects (All domains)
      icon:
        vendor: bs
        name: archive-fill