[[module.imports]]
path = "github.com/hbstack/mermaid"

[[module.imports]]
path = "github.com/hugomods/katex"

[[module.imports]]
path = "github.com/hbstack/bootstrap"

[[module.imports]]
path = "github.com/hugomods/images"

[[module.imports]]
path = "github.com/hugomods/shortcodes"
