[build]
command = "npm ci && hugo --minify --gc -b $URL" # change to suite your needs.
publish = "public"

[build.environment]
NODE_VERSION = "19"
HUGO_VERSION = "0.111.3"
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
GO_VERSION = "1.20"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/zh-hans/*"
  to = "/zh-hans/404.html"
  status = 404

# fallback 404 page.
[[redirects]]
  from = "/*"
  # to = "/404.html"
  to = "/en/404.html" # use this instead if defaultContentLanguageInSubdir is enabled.
  status = 404

  # [module.hugoVersion]
# min = "0.111.3"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/simple-icons"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/font-awesome"

[[module.imports]]
path = "github.com/hbstack/base"

[[module.imports]]
path = "github.com/hbstack/header/modules/language-picker"

[[module.imports]]
path = "github.com/hbstack/header/modules/socials"

[[module.imports]]
path = "github.com/hbstack/header/modules/theme-toggle"

[[module.imports]]
path = "github.com/hbstack/background-image"

[[module.imports]]
path = "github.com/hugomods/seo/modules/favicons"

[params.seo.favicons]
icon = "images/logo.png"

[params.hb.header]

[params.hb.theme_start]
search_input_text = ""