[[module.imports]]
path = "github.com/hbstack/header"

[[module.imports]]
path = "github.com/hbstack/header/modules/language-picker"

[[module.imports]]
path = "github.com/hbstack/header/modules/socials"

[[module.imports]]
path = "github.com/hbstack/header/modules/search"

[[module.imports]]
path = "github.com/hbstack/header/modules/theme-toggle"
