############# English navigation ##############

# main menu
[[main]]
name = "$>home"
url = ""
weight = 1

[[main]]
name = "$>whoami"
url = "whoami/"
weight = 2

[[main]]
name = "$>getintouch"
url = "getintouch/"
weight = 100

[[main]]
name = "#ProjectFOCZOmni"
url = "diary/projectfoczomni/"
weight = 99

[[main]]
name = "$>diary"
url = "#"
weight = 5
hasChildren = true

[[main]]
  parent = "$>diary"
  name = "View my Digital Diary"
  url = "diary/"
  weight = 1

  [[main]]
  parent = "$>diary"
  name = "Awards and Achievements"
  url = "achievements/"
  weight = 2

  [[main]]
  parent = "$>diary"
  name = "Projects"
  url = "projects/"
  weight = 3

# footer menu

[[footer]]
name = "Terms of Use"
url = "terms-of-use/"
weight = 3

[[footer]]
name = "Privacy Statement"
url = "privacy-statement/"
weight = 4

 