#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "150x"
# logo text will only show when logo is missing.
logo_text = "Facets of Conan ZHANG"
# navbar fixed to top
navbar_fixed = true
# OpenGraph / Twitter Card metadata
description = ""
author = "conanzhangtech"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
discordusername = "141732959534317569"
socialusername = "conanzhangtech"
email = "conan.zhang@conanzhang.tech"
# search
search = true

# Posts related Titles & Contents
categories_title = "Categories"
posts_title = "Featured"
featured_post_title = "Featured Post"
recent_post_title = "Recent Post"
featured_post_button = "Featured"
recent_post_button = "Recent"
read_more_button = "$>more"
previous_button = "Previous"
next_button = "Next"
related_posts = "Related Posts"
showing_posts = "You are at:"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"

mainSections = ["blog", "achievements"]
# about widget content
about_widget_content = "My Digital Diary"
# footer content
footer_content = "My Digital Diary"
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""
# copyright
theme_copyright = true
copyright = "Copyright 2025 © Facets of Conan ZHANG"

# 404
error_404_text = "ERROR 404!"
error_404_button = "$>home"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Welcome **!**"
title_small = "to Facets of Conan ZHANG!"
image = "images/banner.png"
background_image = "/images/banner-bg-shape.svg"
content = "My Digital Diary"
button_label = "$>whoami"
button_link = "whoami/"

# Advertise
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
newsletter_title = "Get updated"
newsletter_invitation = "-"
newsletter_placeholder = "Your Email"
newsletter_reminder_a = "By subscribing, You Agree To"
newsletter_reminder_b = "Privacy Statement"
newsletter_button = "Subscribe"
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


############################# social site ########################
[[social]]
title = "mail"
icon = "fa fa-envelope" # themify icon : https://themify.me/themify-icons
link = "mailto:conan.zhang@conanzhang.tech"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://instagram.com/conanzhangtech"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://linkedin.com/in/conanzhangtech"

[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://facebook.com/conanzhang"


[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/conanzhangtech"

[[social]]
title = "discord"
icon = "fab fa-discord" # themify icon : https://themify.me/themify-icons
link = "https://discord.com/user/141732959534317569"