[[module.imports]]
path = "github.com/hbstack/blog"

[[module.imports]]
path = "github.com/hbstack/blog/modules/breadcrumb"

[[module.imports]]
path = "github.com/hbstack/blog/modules/featured-image"

[[module.imports]]
path = "github.com/hbstack/blog/modules/heading-sign"

[[module.imports]]
path = "github.com/hbstack/blog/modules/post-nav"

[[module.imports]]
path = "github.com/hbstack/blog/modules/related-posts"
