[[module.imports]]
path = "github.com/hbstack/meta/blog"

[[module.imports]]
path = "github.com/hbstack/meta/content"

[[module.imports]]
path = "github.com/hbstack/meta/footer"

[[module.imports]]
path = "github.com/hbstack/meta/header"

[[module.imports]]
path = "github.com/hbstack/meta/seo"

[[module.imports]]
path = "github.com/hbstack/syntax-highlighting/styles/gruvbox"
