[[module.imports]]
path = "github.com/hbstack/docs"

[[module.imports]]
path = "github.com/hbstack/docs/modules/breadcrumb"

[[module.imports]]
path = "github.com/hbstack/docs/modules/featured-image"

[[module.imports]]
path = "github.com/hbstack/docs/modules/heading-sign"

[[module.imports]]
path = "github.com/hbstack/docs/modules/doc-nav"
